function [DateTime1,Year1,DoY1,Hour1,NEE1,QFVar1,QFVar_modified1,Ustar1,Tair1,rH1,Rg1,VPD1,LE1,LE_QC,LE_QC_modified,NEE_orig1,NEE_f1,NEE_fqc1,NEE_fall1,NEE_fall_qc1,NEE_fnum1,NEE_fsd1,NEE_fmeth1,NEE_fwin1,Tair_orig1,Tair_f1,Tair_fqc1,Tair_fall1,Tair_fall_qc1,Tair_fnum1,Tair_fsd1,Tair_fmeth1,Tair_fwin1,VPD_orig1,VPD_f1,VPD_fqc1,VPD_fall1,VPD_fall_qc1,VPD_fnum1,VPD_fsd1,VPD_fmeth1,VPD_fwin1,Rg_orig1,Rg_f1,Rg_fqc1,Rg_fall1,Rg_fall_qc1,Rg_fnum1,Rg_fsd1,Rg_fmeth1,Rg_fwin1,LE_orig1,LE_f1,LE_fqc1,LE_fall1,LE_fall_qc1,LE_fnum1,LE_fsd1,LE_fmeth1,LE_fwin1,PotRad_NEW1,FP_VARnight1,FP_VARday1,NEW_FP_Temp1,NEW_FP_VPD1,FP_RRef_Night1,FP_qc1,FP_dRecPar1,FP_errorcode1,FP_GPP1,FP_k1,FP_beta1,FP_alpha1,FP_RRef1,FP_E1,FP_k_sd1,FP_beta_sd1,FP_alpha_sd1,FP_RRef_sd1,FP_E0_sd1,Reco_DT1,GPP_DT1,Reco_DT_SD1,GPP_DT_SD1] = KE_AUS_2019_LE(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [DATETIME1,YEAR1,DOY1,HOUR1,NEE1,QFVAR1,QFVAR_MODIFIED1,USTAR1,TAIR1,RH1,RG1,VPD1,LE1,LE_QC,LE_QC_MODIFIED,NEE_ORIG1,NEE_F1,NEE_FQC1,NEE_FALL1,NEE_FALL_QC1,NEE_FNUM1,NEE_FSD1,NEE_FMETH1,NEE_FWIN1,TAIR_ORIG1,TAIR_F1,TAIR_FQC1,TAIR_FALL1,TAIR_FALL_QC1,TAIR_FNUM1,TAIR_FSD1,TAIR_FMETH1,TAIR_FWIN1,VPD_ORIG1,VPD_F1,VPD_FQC1,VPD_FALL1,VPD_FALL_QC1,VPD_FNUM1,VPD_FSD1,VPD_FMETH1,VPD_FWIN1,RG_ORIG1,RG_F1,RG_FQC1,RG_FALL1,RG_FALL_QC1,RG_FNUM1,RG_FSD1,RG_FMETH1,RG_FWIN1,LE_ORIG1,LE_F1,LE_FQC1,LE_FALL1,LE_FALL_QC1,LE_FNUM1,LE_FSD1,LE_FMETH1,LE_FWIN1,POTRAD_NEW1,FP_VARNIGHT1,FP_VARDAY1,NEW_FP_TEMP1,NEW_FP_VPD1,FP_RREF_NIGHT1,FP_QC1,FP_DRECPAR1,FP_ERRORCODE1,FP_GPP1,FP_K1,FP_BETA1,FP_ALPHA1,FP_RREF1,FP_E1,FP_K_SD1,FP_BETA_SD1,FP_ALPHA_SD1,FP_RREF_SD1,FP_E0_SD1,RECO_DT1,GPP_DT1,RECO_DT_SD1,GPP_DT_SD1]
%   = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [DATETIME1,YEAR1,DOY1,HOUR1,NEE1,QFVAR1,QFVAR_MODIFIED1,USTAR1,TAIR1,RH1,RG1,VPD1,LE1,LE_QC,LE_QC_MODIFIED,NEE_ORIG1,NEE_F1,NEE_FQC1,NEE_FALL1,NEE_FALL_QC1,NEE_FNUM1,NEE_FSD1,NEE_FMETH1,NEE_FWIN1,TAIR_ORIG1,TAIR_F1,TAIR_FQC1,TAIR_FALL1,TAIR_FALL_QC1,TAIR_FNUM1,TAIR_FSD1,TAIR_FMETH1,TAIR_FWIN1,VPD_ORIG1,VPD_F1,VPD_FQC1,VPD_FALL1,VPD_FALL_QC1,VPD_FNUM1,VPD_FSD1,VPD_FMETH1,VPD_FWIN1,RG_ORIG1,RG_F1,RG_FQC1,RG_FALL1,RG_FALL_QC1,RG_FNUM1,RG_FSD1,RG_FMETH1,RG_FWIN1,LE_ORIG1,LE_F1,LE_FQC1,LE_FALL1,LE_FALL_QC1,LE_FNUM1,LE_FSD1,LE_FMETH1,LE_FWIN1,POTRAD_NEW1,FP_VARNIGHT1,FP_VARDAY1,NEW_FP_TEMP1,NEW_FP_VPD1,FP_RREF_NIGHT1,FP_QC1,FP_DRECPAR1,FP_ERRORCODE1,FP_GPP1,FP_K1,FP_BETA1,FP_ALPHA1,FP_RREF1,FP_E1,FP_K_SD1,FP_BETA_SD1,FP_ALPHA_SD1,FP_RREF_SD1,FP_E0_SD1,RECO_DT1,GPP_DT1,RECO_DT_SD1,GPP_DT_SD1]
%   = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [DateTime1,Year1,DoY1,Hour1,NEE1,QFVar1,QFVar_modified1,Ustar1,Tair1,rH1,Rg1,VPD1,LE1,LE_QC,LE_QC_modified,NEE_orig1,NEE_f1,NEE_fqc1,NEE_fall1,NEE_fall_qc1,NEE_fnum1,NEE_fsd1,NEE_fmeth1,NEE_fwin1,Tair_orig1,Tair_f1,Tair_fqc1,Tair_fall1,Tair_fall_qc1,Tair_fnum1,Tair_fsd1,Tair_fmeth1,Tair_fwin1,VPD_orig1,VPD_f1,VPD_fqc1,VPD_fall1,VPD_fall_qc1,VPD_fnum1,VPD_fsd1,VPD_fmeth1,VPD_fwin1,Rg_orig1,Rg_f1,Rg_fqc1,Rg_fall1,Rg_fall_qc1,Rg_fnum1,Rg_fsd1,Rg_fmeth1,Rg_fwin1,LE_orig1,LE_f1,LE_fqc1,LE_fall1,LE_fall_qc1,LE_fnum1,LE_fsd1,LE_fmeth1,LE_fwin1,PotRad_NEW1,FP_VARnight1,FP_VARday1,NEW_FP_Temp1,NEW_FP_VPD1,FP_RRef_Night1,FP_qc1,FP_dRecPar1,FP_errorcode1,FP_GPP1,FP_k1,FP_beta1,FP_alpha1,FP_RRef1,FP_E1,FP_k_sd1,FP_beta_sd1,FP_alpha_sd1,FP_RRef_sd1,FP_E0_sd1,Reco_DT1,GPP_DT1,Reco_DT_SD1,GPP_DT_SD1] = KE_AUS_2019_LE('KEAus_gapfilledNEE_LE.txt',3, 8930);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2023/12/02 21:04:00

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format string for each line of text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Convert the contents of column with dates to serial date numbers using date format string (datenum).
dataArray{1} = datenum(dataArray{1}, 'mm/dd/yyyy HH:MM');

%% Allocate imported array to column variable names
DateTime1 = dataArray{:, 1};
Year1 = dataArray{:, 2};
DoY1 = dataArray{:, 3};
Hour1 = dataArray{:, 4};
NEE1 = dataArray{:, 5};
QFVar1 = dataArray{:, 6};
QFVar_modified1 = dataArray{:, 7};
Ustar1 = dataArray{:, 8};
Tair1 = dataArray{:, 9};
rH1 = dataArray{:, 10};
Rg1 = dataArray{:, 11};
VPD1 = dataArray{:, 12};
LE1 = dataArray{:, 13};
LE_QC = dataArray{:, 14};
LE_QC_modified = dataArray{:, 15};
NEE_orig1 = dataArray{:, 16};
NEE_f1 = dataArray{:, 17};
NEE_fqc1 = dataArray{:, 18};
NEE_fall1 = dataArray{:, 19};
NEE_fall_qc1 = dataArray{:, 20};
NEE_fnum1 = dataArray{:, 21};
NEE_fsd1 = dataArray{:, 22};
NEE_fmeth1 = dataArray{:, 23};
NEE_fwin1 = dataArray{:, 24};
Tair_orig1 = dataArray{:, 25};
Tair_f1 = dataArray{:, 26};
Tair_fqc1 = dataArray{:, 27};
Tair_fall1 = dataArray{:, 28};
Tair_fall_qc1 = dataArray{:, 29};
Tair_fnum1 = dataArray{:, 30};
Tair_fsd1 = dataArray{:, 31};
Tair_fmeth1 = dataArray{:, 32};
Tair_fwin1 = dataArray{:, 33};
VPD_orig1 = dataArray{:, 34};
VPD_f1 = dataArray{:, 35};
VPD_fqc1 = dataArray{:, 36};
VPD_fall1 = dataArray{:, 37};
VPD_fall_qc1 = dataArray{:, 38};
VPD_fnum1 = dataArray{:, 39};
VPD_fsd1 = dataArray{:, 40};
VPD_fmeth1 = dataArray{:, 41};
VPD_fwin1 = dataArray{:, 42};
Rg_orig1 = dataArray{:, 43};
Rg_f1 = dataArray{:, 44};
Rg_fqc1 = dataArray{:, 45};
Rg_fall1 = dataArray{:, 46};
Rg_fall_qc1 = dataArray{:, 47};
Rg_fnum1 = dataArray{:, 48};
Rg_fsd1 = dataArray{:, 49};
Rg_fmeth1 = dataArray{:, 50};
Rg_fwin1 = dataArray{:, 51};
LE_orig1 = dataArray{:, 52};
LE_f1 = dataArray{:, 53};
LE_fqc1 = dataArray{:, 54};
LE_fall1 = dataArray{:, 55};
LE_fall_qc1 = dataArray{:, 56};
LE_fnum1 = dataArray{:, 57};
LE_fsd1 = dataArray{:, 58};
LE_fmeth1 = dataArray{:, 59};
LE_fwin1 = dataArray{:, 60};
PotRad_NEW1 = dataArray{:, 61};
FP_VARnight1 = dataArray{:, 62};
FP_VARday1 = dataArray{:, 63};
NEW_FP_Temp1 = dataArray{:, 64};
NEW_FP_VPD1 = dataArray{:, 65};
FP_RRef_Night1 = dataArray{:, 66};
FP_qc1 = dataArray{:, 67};
FP_dRecPar1 = dataArray{:, 68};
FP_errorcode1 = dataArray{:, 69};
FP_GPP1 = dataArray{:, 70};
FP_k1 = dataArray{:, 71};
FP_beta1 = dataArray{:, 72};
FP_alpha1 = dataArray{:, 73};
FP_RRef1 = dataArray{:, 74};
FP_E1 = dataArray{:, 75};
FP_k_sd1 = dataArray{:, 76};
FP_beta_sd1 = dataArray{:, 77};
FP_alpha_sd1 = dataArray{:, 78};
FP_RRef_sd1 = dataArray{:, 79};
FP_E0_sd1 = dataArray{:, 80};
Reco_DT1 = dataArray{:, 81};
GPP_DT1 = dataArray{:, 82};
Reco_DT_SD1 = dataArray{:, 83};
GPP_DT_SD1 = dataArray{:, 84};

