function [DateTime,Year,DoY,Hour,NEE,QFVar,QFVar_modified,Ustar,Tair,rH,Rg,VPD,LE,qc_LE,qc_LEmodified,NEE_orig,NEE_f,NEE_fqc,NEE_fall,NEE_fall_qc,NEE_fnum,NEE_fsd,NEE_fmeth,NEE_fwin,Tair_orig,Tair_f,Tair_fqc,Tair_fall,Tair_fall_qc,Tair_fnum,Tair_fsd,Tair_fmeth,Tair_fwin,VPD_orig,VPD_f,VPD_fqc,VPD_fall,VPD_fall_qc,VPD_fnum,VPD_fsd,VPD_fmeth,VPD_fwin,Rg_orig,Rg_f,Rg_fqc,Rg_fall,Rg_fall_qc,Rg_fnum,Rg_fsd,Rg_fmeth,Rg_fwin,LE_orig,LE_f,LE_fqc,LE_fall,LE_fall_qc,LE_fnum,LE_fsd,LE_fmeth,LE_fwin,PotRad_NEW,FP_VARnight,FP_VARday,NEW_FP_Temp,NEW_FP_VPD,FP_RRef_Night,FP_qc,FP_dRecPar,FP_errorcode,FP_GPP2000,FP_k,FP_beta,FP_alpha,FP_RRef,FP_E0,FP_k_sd,FP_beta_sd,FP_alpha_sd,FP_RRef_sd,FP_E0_sd,Reco_DT,GPP_DT,Reco_DT_SD,GPP_DT_SD] = KE_KAP_2019_Mar_Oct_LE(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [DATETIME,YEAR1,DOY,HOUR1,NEE,QFVAR,QFVAR_MODIFIED,USTAR,TAIR,RH,RG,VPD,LE,QC_LE,QC_LEMODIFIED,NEE_ORIG,NEE_F,NEE_FQC,NEE_FALL,NEE_FALL_QC,NEE_FNUM,NEE_FSD,NEE_FMETH,NEE_FWIN,TAIR_ORIG,TAIR_F,TAIR_FQC,TAIR_FALL,TAIR_FALL_QC,TAIR_FNUM,TAIR_FSD,TAIR_FMETH,TAIR_FWIN,VPD_ORIG,VPD_F,VPD_FQC,VPD_FALL,VPD_FALL_QC,VPD_FNUM,VPD_FSD,VPD_FMETH,VPD_FWIN,RG_ORIG,RG_F,RG_FQC,RG_FALL,RG_FALL_QC,RG_FNUM,RG_FSD,RG_FMETH,RG_FWIN,LE_ORIG,LE_F,LE_FQC,LE_FALL,LE_FALL_QC,LE_FNUM,LE_FSD,LE_FMETH,LE_FWIN,POTRAD_NEW,FP_VARNIGHT,FP_VARDAY,NEW_FP_TEMP,NEW_FP_VPD,FP_RREF_NIGHT,FP_QC,FP_DRECPAR,FP_ERRORCODE,FP_GPP2000,FP_K,FP_BETA,FP_ALPHA,FP_RREF,FP_E0,FP_K_SD,FP_BETA_SD,FP_ALPHA_SD,FP_RREF_SD,FP_E0_SD,RECO_DT,GPP_DT,RECO_DT_SD,GPP_DT_SD]
%   = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [DATETIME,YEAR1,DOY,HOUR1,NEE,QFVAR,QFVAR_MODIFIED,USTAR,TAIR,RH,RG,VPD,LE,QC_LE,QC_LEMODIFIED,NEE_ORIG,NEE_F,NEE_FQC,NEE_FALL,NEE_FALL_QC,NEE_FNUM,NEE_FSD,NEE_FMETH,NEE_FWIN,TAIR_ORIG,TAIR_F,TAIR_FQC,TAIR_FALL,TAIR_FALL_QC,TAIR_FNUM,TAIR_FSD,TAIR_FMETH,TAIR_FWIN,VPD_ORIG,VPD_F,VPD_FQC,VPD_FALL,VPD_FALL_QC,VPD_FNUM,VPD_FSD,VPD_FMETH,VPD_FWIN,RG_ORIG,RG_F,RG_FQC,RG_FALL,RG_FALL_QC,RG_FNUM,RG_FSD,RG_FMETH,RG_FWIN,LE_ORIG,LE_F,LE_FQC,LE_FALL,LE_FALL_QC,LE_FNUM,LE_FSD,LE_FMETH,LE_FWIN,POTRAD_NEW,FP_VARNIGHT,FP_VARDAY,NEW_FP_TEMP,NEW_FP_VPD,FP_RREF_NIGHT,FP_QC,FP_DRECPAR,FP_ERRORCODE,FP_GPP2000,FP_K,FP_BETA,FP_ALPHA,FP_RREF,FP_E0,FP_K_SD,FP_BETA_SD,FP_ALPHA_SD,FP_RREF_SD,FP_E0_SD,RECO_DT,GPP_DT,RECO_DT_SD,GPP_DT_SD]
%   = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [DateTime,Year1,DoY,Hour1,NEE,QFVar,QFVar_modified,Ustar,Tair,rH,Rg,VPD,LE,qc_LE,qc_LEmodified,NEE_orig,NEE_f,NEE_fqc,NEE_fall,NEE_fall_qc,NEE_fnum,NEE_fsd,NEE_fmeth,NEE_fwin,Tair_orig,Tair_f,Tair_fqc,Tair_fall,Tair_fall_qc,Tair_fnum,Tair_fsd,Tair_fmeth,Tair_fwin,VPD_orig,VPD_f,VPD_fqc,VPD_fall,VPD_fall_qc,VPD_fnum,VPD_fsd,VPD_fmeth,VPD_fwin,Rg_orig,Rg_f,Rg_fqc,Rg_fall,Rg_fall_qc,Rg_fnum,Rg_fsd,Rg_fmeth,Rg_fwin,LE_orig,LE_f,LE_fqc,LE_fall,LE_fall_qc,LE_fnum,LE_fsd,LE_fmeth,LE_fwin,PotRad_NEW,FP_VARnight,FP_VARday,NEW_FP_Temp,NEW_FP_VPD,FP_RRef_Night,FP_qc,FP_dRecPar,FP_errorcode,FP_GPP2000,FP_k,FP_beta,FP_alpha,FP_RRef,FP_E0,FP_k_sd,FP_beta_sd,FP_alpha_sd,FP_RRef_sd,FP_E0_sd,Reco_DT,GPP_DT,Reco_DT_SD,GPP_DT_SD]= KE_KAP_2019_Mar_Oct_LE('KEKap_gapfilledNEE_LE_2.txt',3, 8930);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2023/12/02 20:53:02

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format string for each line of text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Convert the contents of column with dates to serial date numbers using date format string (datenum).
dataArray{1} = datenum(dataArray{1}, 'mm/dd/yyyy HH:MM');

%% Allocate imported array to column variable names
DateTime = dataArray{:, 1};
Year = dataArray{:, 2};
DoY = dataArray{:, 3};
Hour = dataArray{:, 4};
NEE = dataArray{:, 5};
QFVar = dataArray{:, 6};
QFVar_modified = dataArray{:, 7};
Ustar = dataArray{:, 8};
Tair = dataArray{:, 9};
rH = dataArray{:, 10};
Rg = dataArray{:, 11};
VPD = dataArray{:, 12};
LE = dataArray{:, 13};
qc_LE = dataArray{:, 14};
qc_LEmodified = dataArray{:, 15};
NEE_orig = dataArray{:, 16};
NEE_f = dataArray{:, 17};
NEE_fqc = dataArray{:, 18};
NEE_fall = dataArray{:, 19};
NEE_fall_qc = dataArray{:, 20};
NEE_fnum = dataArray{:, 21};
NEE_fsd = dataArray{:, 22};
NEE_fmeth = dataArray{:, 23};
NEE_fwin = dataArray{:, 24};
Tair_orig = dataArray{:, 25};
Tair_f = dataArray{:, 26};
Tair_fqc = dataArray{:, 27};
Tair_fall = dataArray{:, 28};
Tair_fall_qc = dataArray{:, 29};
Tair_fnum = dataArray{:, 30};
Tair_fsd = dataArray{:, 31};
Tair_fmeth = dataArray{:, 32};
Tair_fwin = dataArray{:, 33};
VPD_orig = dataArray{:, 34};
VPD_f = dataArray{:, 35};
VPD_fqc = dataArray{:, 36};
VPD_fall = dataArray{:, 37};
VPD_fall_qc = dataArray{:, 38};
VPD_fnum = dataArray{:, 39};
VPD_fsd = dataArray{:, 40};
VPD_fmeth = dataArray{:, 41};
VPD_fwin = dataArray{:, 42};
Rg_orig = dataArray{:, 43};
Rg_f = dataArray{:, 44};
Rg_fqc = dataArray{:, 45};
Rg_fall = dataArray{:, 46};
Rg_fall_qc = dataArray{:, 47};
Rg_fnum = dataArray{:, 48};
Rg_fsd = dataArray{:, 49};
Rg_fmeth = dataArray{:, 50};
Rg_fwin = dataArray{:, 51};
LE_orig = dataArray{:, 52};
LE_f = dataArray{:, 53};
LE_fqc = dataArray{:, 54};
LE_fall = dataArray{:, 55};
LE_fall_qc = dataArray{:, 56};
LE_fnum = dataArray{:, 57};
LE_fsd = dataArray{:, 58};
LE_fmeth = dataArray{:, 59};
LE_fwin = dataArray{:, 60};
PotRad_NEW = dataArray{:, 61};
FP_VARnight = dataArray{:, 62};
FP_VARday = dataArray{:, 63};
NEW_FP_Temp = dataArray{:, 64};
NEW_FP_VPD = dataArray{:, 65};
FP_RRef_Night = dataArray{:, 66};
FP_qc = dataArray{:, 67};
FP_dRecPar = dataArray{:, 68};
FP_errorcode = dataArray{:, 69};
FP_GPP2000 = dataArray{:, 70};
FP_k = dataArray{:, 71};
FP_beta = dataArray{:, 72};
FP_alpha = dataArray{:, 73};
FP_RRef = dataArray{:, 74};
FP_E0 = dataArray{:, 75};
FP_k_sd = dataArray{:, 76};
FP_beta_sd = dataArray{:, 77};
FP_alpha_sd = dataArray{:, 78};
FP_RRef_sd = dataArray{:, 79};
FP_E0_sd = dataArray{:, 80};
Reco_DT = dataArray{:, 81};
GPP_DT = dataArray{:, 82};
Reco_DT_SD = dataArray{:, 83};
GPP_DT_SD = dataArray{:, 84};

